ndarray.ndim
the number of axes (dimensions) of the array.

ndarray.shape
the dimensions of the array.

ndarray.size
the total number of elements of the array. 

ndarray.dtype
an object describing the type of the elements in the array.

In [25]:
import numpy as np
a = np.array([2,3,4])
a
type(a)
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
np.zeros((3, 4))
np.ones((2, 3, 4), dtype=np.int16)

np.empty((2, 3)) 

array([[1.39069238e-309, 1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309, 1.39069238e-309]])

To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

In [27]:
np.arange(10, 30, 5)
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [28]:
from numpy import pi
np.linspace(0, 2, 9)                   # 9 numbers from 0 to 2
x = np.linspace(0, 2 * pi, 100)  # useful to evaluate function at lots of points
f= np.sin(x)

PRINTING ARRAYS

In [29]:
a = np.arange(6)                    # 1d array
print(a)
b = np.arange(12).reshape(4, 3)     # 2d array
print(b)
c = np.arange(24).reshape(2, 3, 4)  # 3d array
print(c)


[0 1 2 3 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Basic operations

In [30]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b
c = a - b
c
b**2
10 * np.sin(a)
a < 35

array([ True,  True, False, False])

In [31]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product
A @ B     # matrix product
A.dot(B)  # another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [32]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name
c = a + b
c
c.dtype.name
d = np.exp(c * 1j)
d
d.dtype.name

'complex128'

In [34]:
rg = np.random.default_rng(1)
a = rg.random((2, 3))
a
a.sum()
a.min()
a.max()
b = np.arange(12).reshape(3, 4)
b
b.sum(axis=0)     # sum of each column
b.min(axis=1)     # min of each row
b.cumsum(axis=1)  # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

Universal functions


In [35]:
B = np.arange(3)
B
np.exp(B)
np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

Indexing, slicing and iterating


In [36]:
a = np.arange(10)**3
a
a[2]
a[2:5]
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a
a[::-1]  # reversed a
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [37]:
def f(x, y):
    return 10 * x + y
b = np.fromfunction(f, (5, 4), dtype=int)
b
b[2, 3]
b[0:5, 1]  # each row in the second column of b
b[:, 1]    # equivalent to the previous example
b[1:3, :]  # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [39]:
a = np.floor(10 * rg.random((3, 4)))

a.ravel()  # returns the array, flattened
a.reshape(6, 2)  # returns the array with a modified shape
a.T  # returns the array, transposed
a.T.shape
a.shape

(3, 4)

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:



In [ ]:
a
a.resize((2, 6))
a

: 

In [1]:
import numpy as np

# Creating a vector
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

# Vector Addition
print(v + w)  # [5, 7, 9]

[5 7 9]


In [2]:
import numpy as np

# Creating a vector
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

# Vector Addition
print(v + w)  # [5, 7, 9]

[5 7 9]


In [3]:
# Method 1: The @ operator (most common in modern Python)
dot_product = v @ w 

# Method 2: np.dot()
dot_product_alt = np.dot(v, w)

print(dot_product) # 1*4 + 2*5 + 3*6 = 32

32


In [1]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# This does the row-by-column math automatically
result = A @ B

print(result) 
# Output: [[19 22]
#          [43 50]]

[[19 22]
 [43 50]]
